config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :events
  resources :event_types
  resources :users
  get "monthly_report" => "events#monthly_report"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billpaiduser.rb
class Billpaiduser < ApplicationRecord
	belongs_to :event,optional: true
	belongs_to :user

	validates :paid_amt,numericality: { greater_than_or_equal_to: 1 }

end

app/models/concerns/commonvalidation.rb
module Commonvalidation
	extend ActiveSupport::Concern

	included do
		validates :name,:presence => true
	end

end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :event_type

	has_many :billpaidusers,dependent: :destroy
	accepts_nested_attributes_for :billpaidusers,:allow_destroy => true

	validates :event_type_id,:event_date,:presence => true
	validates :total_amount,numericality: { greater_than_or_equal_to: 1 }
	validates :billpaidusers,:presence => true

	HUMANIZED_ATTRIBUTES = {:billpaidusers => "Users",:"billpaidusers.user" => "Users",:"billpaidusers.paid_amt" => "Paid Amount"}
	def self.human_attribute_name(attr, options={})
		puts "------ATTR----#{attr.inspect}----options-----#{options.inspect}-------"
	    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
	end

end

app/models/event_type.rb
class EventType < ApplicationRecord
	include Commonvalidation
end

app/models/user.rb
class User < ApplicationRecord
	include Commonvalidation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  before_action :set_event_type, only: [:show, :edit, :update, :destroy]

  # GET /event_types
  # GET /event_types.json
  def index
    @event_types = EventType.all
  end

  # GET /event_types/1
  # GET /event_types/1.json
  def show
  end

  # GET /event_types/new
  def new
    @event_type = EventType.new
  end

  # GET /event_types/1/edit
  def edit
  end

  # POST /event_types
  # POST /event_types.json
  def create
    @event_type = EventType.new(event_type_params)

    respond_to do |format|
      if @event_type.save
        format.html { redirect_to event_types_path, notice: 'Event type was successfully created.' }
        format.json { render :show, status: :created, location: @event_type }
      else
        format.html { render :new }
        format.json { render json: @event_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_types/1
  # PATCH/PUT /event_types/1.json
  def update
    respond_to do |format|
      if @event_type.update(event_type_params)
        format.html { redirect_to event_types_path, notice: 'Event type was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_type }
      else
        format.html { render :edit }
        format.json { render json: @event_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_types/1
  # DELETE /event_types/1.json
  def destroy
    @event_type.destroy
    respond_to do |format|
      format.html { redirect_to event_types_url, notice: 'Event type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_type
      @event_type = EventType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_type_params
      params.require(:event_type).permit(:name)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save

        # Rails.logger.info "-----BILL PAID USER-------#{params[:billpaidusers]}----"
        # unless params[:billpaidusers].blank?
        #   params[:billpaidusers].each do |paid_user|
        #     Rails.logger.info "-----BILL PAID USER-----k--#{[paid_user]["is_attended"]}-----"
        #   end  
        # end
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def monthly_report
    @monthly_reports = Event.all.group_by {|t| t.event_date.beginning_of_month} 
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_date, :location, :total_amount, :event_type_id,billpaidusers_attributes: [:id, :event_id,:user_id,:paid_amt,:is_attended, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_types_helper.rb
module EventTypesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_types/_form.html.erb
<%= form_for @event_type, :html => { :class => "form-horizontal event_type" } do |f| %>

  <% if @event_type.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event_type.errors.count, "error") %> prohibited this event_type from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event_type.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                event_types_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/event_types/edit.html.erb
<%- model_class = EventType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/event_types/index.html.erb
<%- model_class = EventType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @event_types.each do |event_type| %>
      <tr>
        <td><%= event_type.name %></td>
        <td>
          <%= link_to "Edit",edit_event_type_path(event_type), :class => 'btn btn-default btn-xs' %>
          <%= link_to "Destroy",
                      event_type_path(event_type),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure?'},
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New",new_event_type_path,:class => 'btn btn-primary' %>

app/views/event_types/new.html.erb
<%- model_class = EventType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/event_types/show.html.erb
<%- model_class = EventType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event_type.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              event_types_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_type_path(@event_type), :class => 'btn btn-default' %>

app/views/events/_form.html.erb
<%= nested_form_for @event, :html => { :class => "form-horizontal event" } do |f| %>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :event_type_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :event_type_id,EventType.all.collect {|et| [et.name,et.id]},{:include_blank => "Select Event Type"},{:class => 'form-control' }%>
    </div>
    <%=f.error_span(:event_type_id) %>
  </div>
  <div class="form-group">
    <%= f.label :event_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :event_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:event_date) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :total_amount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :total_amount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:total_amount) %>
  </div>
  <hr>
  <h3>Bill Payment</h3>
  <%= f.fields_for :billpaidusers do |user_form| %>
    <div class="form-group">
      <div class="col-lg-offset-2">
        <%= user_form.select :user_id,User.all.collect {|user| [user.name,user.id] },{:include_blank => "Select user"},:class => "form-control" %>
      </div>  
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2">
        <%= user_form.number_field :paid_amt,:placeholder => "Enter Paid Amount",:class => "form-control" %>    
      </div>
    </div>
    
    <%= user_form.link_to_remove "Remove this user",:class => "btn btn-link" %>
  <% end %>
  <p><%= f.link_to_add "Add a user", :billpaidusers,:class => "btn btn-link" %></p>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),events_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:event_date) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:total_amount) %></th>
      <th><%= model_class.human_attribute_name(:event_type_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_date.blank? ? "" : event.event_date.strftime("%d %B, %Y") %></td>
        <td><%= event.location %></td>
        <td><%= event.total_amount %></td>
        <td><%= event.event_type.name %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/monthly_report.html.erb
<!--
<div class="page-header">
  <h1>Monthy Report</h1>
</div>
<% @monthly_reports.each do |month_date,rep_data| %>
  <dl class="dl-horizontal">
    <dt>
      <stro
        ng><%= month_date.strftime("%B-%Y") %></strong>
      <% rep_data.each do |data| %>
        <dd> 
          <strong><%= data.event_type.name %></strong>
        </dd> 
        <dd>
          <%= data.total_amount %>
        </dd>
        <% data.billpaidusers.each do |bill_obj| %>
          <dd>
            <%= bill_obj.user.name %> Paid Rs.<%= bill_obj.paid_amt  %>
          </dd>
        <% end %>
        <br>
      <% end %>      
    </dt>  
  </dl>
  <hr>
<% end %>
-->

<div class="page-header">
  <h1>Monthly Report</h1>
</div>
<% @monthly_reports.each do |month_date,rep_data| %>
  <dl class="dl-horizontal">
    <dt>
      <strong><%= month_date.strftime("%B-%Y") %></strong>
      <% rep_data.each do |data| %>
        <dd> 
          <strong><%= data.event_type.name %></strong>
        </dd> 
        <dd>
          <strong>Total:</strong>&nbsp;<%= data.total_amount %>
        </dd>
        <% contri = data.total_amount/data.billpaidusers.count %>
        <% user_hash_pos = Hash.new %>
        <% user_hash_neg = Hash.new %>
        <% data.billpaidusers.each do |bill_obj| %>
          <dd>
            <%= bill_obj.user.name %> Paid Rs.<%= bill_obj.paid_amt  %>
          </dd>
          <% if contri > bill_obj.paid_amt
            user_hash_pos["#{bill_obj.user.name}"] = contri - bill_obj.paid_amt
          else
            user_hash_neg["#{bill_obj.user.name}"] = bill_obj.paid_amt - contri
          end %>
        <% end %>
        <br>
        <% user_hash_pos.each do |k,v| %>
          <% user_hash_neg.each do |k1,v1| %>
            <% if v1 > contri
              paid_val = v 
            else
              paid_val = v1
            end %>
            <dd><%= k %> Paid <%= paid_val %> to <%= k1 %></dd>
          <% end %> 
        <% end %>
        ----------------------------------------------------------------
        
      <% end %>      
    </dt>  
  </dl>
  <hr>
<% end %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:event_date) %>:</strong></dt>
  <dd><%= @event.event_date.strftime("%d %B, %Y") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @event.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_amount) %>:</strong></dt>
  <dd><%= @event.total_amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_type_id) %>:</strong></dt>
  <dd><%= @event.event_type.name %></dd>
  <dt><strong>Bill Paid Users:</strong></dt>
  <dd><% @event.billpaidusers.each do |bill| %>
      <%= bill.user.name %> <strong>Paid</strong> Rs. <%= bill.paid_amt %><br>
    <% end %>    
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),events_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),edit_event_path(@event), :class => 'btn btn-default' %>

app/views/home/index.html.erb
<h1>Welcome To Event Billing App</h1>
<div class="footer">
  <p>Copyright 2018: Developed by Amol D</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Billing System" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <a class="navbar-brand" href="<%= root_path %>">Home</a>
        <a class="navbar-brand" href="<%= users_path %>">Users</a>
        <a class="navbar-brand" href="<%= event_types_path %>">Event Type</a>
        <a class="navbar-brand" href="<%= events_path %>">Events</a>
        <a class="navbar-brand" href="<%= monthly_report_path %>">Monthly Report</a>
      </div>
    </div>
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>